### ISSUE TITLE
New to Node-red: Question about Action node

### ISSUE THREAD

**Issue by davismm85** [emiliobool/node-red-contrib-twitch-chat#6]
I want to first say thank you so much for developing this. it has helped me a lot, even though I don't know really anything about node.js

I was hoping to reach out with a question for support, since this isn't an issue related, it is more of confusion on my end.

In node red, i want to use the action node to post a message in my Twitch Chat. I am pretty sure I need to use the function node with the action node, but I am unsure how to pass through what I want exactly.

I read the documentation:
Parameters:
channel: String - Channel name (Required)
message: String - Message (Required)
client.action("channel", "Your message");

I just don't understand how I can get it working correctly. I am currently using an Input to try to pass TEST into my twitch chat. What should I pass through the function (if i even use that)

Thank you so much in advance for reading this. If this is not the right area to post this please let me know how I can get in touch to help me out with this

Thanks,
Matt

**Comment by emiliobool** [comment]
Hi, so the action node is meant for action messages, the ones shown with your username's color and that you type in chat like "/me message... ". If that's what you want then that's what you can use. If instead you want to send a regular message then you need the "say" node. Both accept the same payload so from a function node you just need to make sure to return the message:

`{
payload: {
message: "Your message",
channel: "yourchannel"
}`

You don't have to use a function node, you can also use any other node that lets you set the payload values and change "message" and "channel". 

You can also use the inject node for testing and just set the payload as json:

`{ "channel": "yourchannel", "message": "your message" }`

**Comment by davismm85** [comment]
You are the best :-) Thank you for clearing this up for me. Have a great weekend!!
