### ISSUE TITLE
"TypeError: Cannot read property 'startsWith' of undefined"

### ISSUE THREAD

**Issue by TaylorTMusic** [emiliobool/node-red-contrib-twitch-chat#7]
I'm trying to send a message from this to my Chat with the "Say" node. Can you provide an example of what to inject that the node will accept. Current error is:

"TypeError: Cannot read property 'startsWith' of undefined"

**Comment by emiliobool** [comment]
hi, the payload needs to be 

```
{
"channel": "channelname", 
"message" "message text"
}
```

**Comment by TaylorTMusic** [comment]
That did it! Sorry for the basic question
